---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qijun.
--- DateTime: 2020/2/1 15:44
---
local _M ={}
_M._VERSION = '1.0'
local mt = {__index = _M}
local function func2()
    print(gName)
end
function _M.function1()
    return func2()
end

return _M